// web/src/lib/components/search-form.svelte
<script>
  import { detectMode } from "$lib/query-mode";

  const DEBOUNCE_MS = 300;

  let { value = "", onSearch, onClear, disabled = false, examples = [] } = $props();

  // A writable derived: it follows the owner's value — which is bound to the
  // URL, so a deep link or the clear button flows in — and typing overrides it
  // until the next external change.
  let query = $derived(value);
  let input = $state(null);
  let timer;

  const detected = $derived(detectMode(query));
  const canSearch = $derived(detected.mode === "sbd" || detected.mode === "name");

  // Debounced live search.
  $effect(() => {
    const q = query;
    const mode = detected.mode;
    clearTimeout(timer);

    if (mode !== "sbd" && mode !== "name") {
      if (mode === "empty") onClear?.();
      return;
    }
    // Already showing results for this query — happens when the value flows in
    // from URL hydration.
    if (q.trim() === value.trim() && q.trim() !== "") return;

    timer = setTimeout(() => onSearch(q.trim()), DEBOUNCE_MS);
    return () => clearTimeout(timer);
  });

  function submit(event) {
    event.preventDefault();
    if (!canSearch) return;
    clearTimeout(timer);
    onSearch(query.trim());
  }

  function clear() {
    query = "";
    input?.focus();
  }
</script>

<form onsubmit={submit} class="mx-auto mb-6 flex max-w-[640px] flex-col gap-1.5" role="search">
  <label for="search-input" class="text-sm font-semibold tracking-wider text-ink-muted uppercase">
    Tra cứu điểm
  </label>

  <div class="flex gap-2 max-sm:flex-col">
    <div class="relative flex flex-1 items-center">
      <input
        id="search-input"
        bind:this={input}
        bind:value={query}
        type="search"
        inputmode="search"
        class="field pr-9 [&::-webkit-search-cancel-button]:hidden"
        placeholder="Ví dụ: 47006585 hoặc Nguyen Van An"
        {disabled}
        autocomplete="off"
        spellcheck="false"
        aria-describedby="search-hint"
      />
      {#if query}
        <button
          type="button"
          class="absolute right-1.5 flex h-7 w-7 cursor-pointer items-center justify-center
                 rounded-full border-0 bg-transparent text-xl leading-none text-ink-muted
                 transition-colors hover:bg-surface-alt hover:text-ink"
          onclick={clear}
          aria-label="Xoá tìm kiếm"
          tabindex="-1"
        >
          ×
        </button>
      {/if}
    </div>

    <button type="submit" class="btn-primary max-sm:w-full" disabled={disabled || !canSearch}>
      Tra cứu
    </button>
  </div>

  <p
    id="search-hint"
    class="m-0 min-h-[1.2em] text-sm transition-colors"
    class:text-ink-muted={detected.mode !== "sbd-short" && detected.mode !== "name-short"}
    class:text-[color:var(--tier-legendary-accent)]={detected.mode === "sbd-short" ||
      detected.mode === "name-short"}
    aria-live="polite"
  >
    {detected.hint}{#if detected.mode === "empty"} · VD: {#each examples as example, i (example)}<button
          type="button"
          class="btn-chip"
          onclick={() => {
            query = example;
            input?.focus();
          }}>{example}</button
        >{i < examples.length - 1 ? " hoặc " : ""}{/each}{/if}
  </p>
</form>

// 2017/src/components/search-form.jsx
import { useEffect, useRef, useState } from "react";

const DEBOUNCE_MS = 300;
const MIN_SBD_DIGITS = 3;
const MIN_NAME_CHARS = 2;
const EXAMPLES = ["49008235", "Nguyễn Minh Tiến"];

// Detect input mode for dynamic hint shown under the field
function detectMode(raw) {
  const q = raw.trim();
  if (!q) return { mode: "empty", hint: "Gõ SBD (chữ số) hoặc họ tên để tìm" };
  if (/^\d+$/.test(q)) {
    return q.length >= MIN_SBD_DIGITS
      ? { mode: "sbd", hint: `Tìm theo số báo danh · khớp chính xác` }
      : { mode: "sbd-short", hint: `Cần ít nhất ${MIN_SBD_DIGITS} chữ số` };
  }
  return q.length >= MIN_NAME_CHARS
    ? { mode: "name", hint: "Tìm theo họ tên · không phân biệt dấu và hoa/thường" }
    : { mode: "name-short", hint: `Cần ít nhất ${MIN_NAME_CHARS} ký tự` };
}

export function SearchForm({ onSearch, onClear, disabled }) {
  const [query, setQuery] = useState("");
  const inputRef = useRef(null);
  const timerRef = useRef(null);
  const { mode, hint } = detectMode(query);
  const canSearch = mode === "sbd" || mode === "name";

  // Debounced live search
  useEffect(() => {
    clearTimeout(timerRef.current);
    if (!canSearch) {
      if (mode === "empty") onClear?.();
      return;
    }
    timerRef.current = setTimeout(() => onSearch(query.trim()), DEBOUNCE_MS);
    return () => clearTimeout(timerRef.current);
  }, [query, canSearch, mode, onSearch, onClear]);

  function handleSubmit(e) {
    e.preventDefault();
    if (canSearch) {
      clearTimeout(timerRef.current);
      onSearch(query.trim());
    }
  }

  function handleClear() {
    setQuery("");
    inputRef.current?.focus();
  }

  return (
    <form onSubmit={handleSubmit} className="search-form" role="search">
      <label htmlFor="search-input" className="search-label">
        Tra cứu điểm
      </label>
      <div className="search-input-row">
        <div className={`search-input-wrap mode-${mode}`}>
          <input
            id="search-input"
            ref={inputRef}
            type="search"
            inputMode="search"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Ví dụ: 47006585 hoặc Nguyen Van An"
            disabled={disabled}
            autoFocus
            autoComplete="off"
            spellCheck={false}
            aria-describedby="search-hint"
          />
          {query && (
            <button
              type="button"
              className="clear-btn"
              onClick={handleClear}
              aria-label="Xoá tìm kiếm"
              tabIndex={-1}
            >
              ×
            </button>
          )}
        </div>
        <button
          type="submit"
          className="primary-btn"
          disabled={disabled || !canSearch}
        >
          Tra cứu
        </button>
      </div>
      <p id="search-hint" className={`search-hint mode-${mode}`} aria-live="polite">
        {hint}
        {mode === "empty" && (
          <>
            {" · VD: "}
            {EXAMPLES.map((ex, i) => (
              <span key={ex}>
                <button
                  type="button"
                  className="example-btn"
                  onClick={() => {
                    setQuery(ex);
                    inputRef.current?.focus();
                  }}
                >
                  {ex}
                </button>
                {i < EXAMPLES.length - 1 ? " hoặc " : ""}
              </span>
            ))}
          </>
        )}
      </p>
    </form>
  );
}
